services:
  eventstore:
    image: eventstore/eventstore:24.10
    container_name: eventstore
    environment:
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INT_TCP_PORT=1113
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
      - "1113:1113"
    restart: unless-stopped
    networks:
      - pm_pdp

  admin-pdp-epp:
    image: csd773/pm-admin-pdp-epp
    environment:
      - GRPC_SERVER_PORT=50052
      - PM_PDP_ADMIN_BOOTSTRAP_FILE_PATH=/config/bootstrap.json
      - PM_PDP_ADMIN_BOOTSTRAP_USER=u1
      - PM_PDP_ADMIN_NEO4J_DB_PATH=/tmp/neo4j
      - PM_PDP_ADMIN_ESDB_CONSUMER_GROUP=admin-pdp-epp-cg
      - PM_PDP_ADMIN_SNAPSHOT_INTERVAL=1000
      - PM_PDP_ADMIN_SHUTDOWN_AFTER_BOOTSTRAP=false
      - PM_PDP_ESDB_HOSTNAME=eventstore
      - PM_PDP_ESDB_PORT=2113
      - PM_PDP_ESDB_EVENT_STREAM=pm-events-v1
      - PM_PDP_ESDB_SNAPSHOT_STREAM=pm-snapshot-v1
    ports:
      - "50052:50052"
    volumes:
      - ./bootstrap.json:/config/bootstrap.json
    restart: unless-stopped
    networks:
      - pm_pdp

  resource-pdp:
    image: csd773/pm-resource-pdp
    environment:
      - GRPC_SERVER_PORT=50051
      - PM_PDP_RESOURCE_ADMIN_HOSTNAME=admin-pdp-epp
      - PM_PDP_RESOURCE_ADMIN_PORT=50052
      - PM_PDP_ESDB_HOSTNAME=eventstore
      - PM_PDP_ESDB_PORT=2113
      - PM_PDP_ESDB_EVENT_STREAM=pm-events-v1
      - PM_PDP_ESDB_SNAPSHOT_STREAM=pm-snapshot-v1
      - PM_PDP_RESOURCE_EPP_MODE=DISABLED
    ports:
      - "50051:50051"
    restart: unless-stopped
    networks:
      - pm_pdp

networks:
  pm_pdp:
    name: pm_pdp