services:
  eventstore:
    image: eventstore/eventstore:24.10
    container_name: eventstore
    environment:
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INT_TCP_PORT=1113
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - ./eventstore-data:/var/lib/eventstore
      - ./eventstore-logs:/var/log/eventstore
    restart: unless-stopped
    networks:
      - pm_pdp

  admin-pdp-epp:
    image: csd773/pm.server.admin-pdp-epp:latest
    pull_policy: always
    environment:
      - ADMIN_GRPC_SERVER_PORT=50052
      - ESDB_HOST=eventstore
      - ESDB_PORT=2113
      - BOOTSTRAP_FILE_PATH=/config/bootstrap.pml
      - BOOTSTRAP_USER=u1
    ports:
      - "50052:50052"
    depends_on:
      - eventstore
    volumes:
      - ./bootstrap.pml:/config/bootstrap.pml
    restart: unless-stopped
    networks:
      - pm_pdp

  resource-pdp:
    image: csd773/pm.server.resource-pdp:latest
    pull_policy: always
    environment:
      - RESOURCE_GRPC_SERVER_PORT=50051
      - ADMIN_GRPC_SERVER_HOST=admin-pdp-epp
      - ADMIN_GRPC_SERVER_PORT=50052
      - ESDB_HOST=eventstore
      - ESDB_PORT=2113
    ports:
      - "50051:50051"
    depends_on:
      - eventstore
    restart: unless-stopped
    networks:
      - pm_pdp

volumes:
  eventstore-data:
  eventstore-logs:

networks:
  pm_pdp:
    name: pm_pdp