package gov.nist.csd.pm.pdp.admin.pdp;

import com.eventstore.dbclient.WrongExpectedVersionException;
import gov.nist.csd.pm.core.common.exception.PMException;
import gov.nist.csd.pm.core.common.exception.PMRuntimeException;
import gov.nist.csd.pm.core.pap.query.model.context.UserContext;
import gov.nist.csd.pm.pdp.admin.pap.EventTrackingPAP;
import gov.nist.csd.pm.pdp.proto.event.PMEvent;
import gov.nist.csd.pm.pdp.shared.eventstore.CurrentRevisionService;
import gov.nist.csd.pm.pdp.shared.eventstore.EventStoreConnectionManager;
import gov.nist.csd.pm.pdp.shared.eventstore.EventStoreDBConfig;
import gov.nist.csd.pm.proto.v1.cmd.AdminCommand;
import gov.nist.csd.pm.proto.v1.model.Value;
import io.github.resilience4j.retry.Retry;
import io.github.resilience4j.retry.RetryConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

@Component
public class Adjudicator {

    private static final Logger logger = LoggerFactory.getLogger(Adjudicator.class);

    private final CommandHandler commandHandler;
    private final CurrentRevisionService currentRevision;
    private final Retry retry;
    private final EventStoreDBConfig eventStoreDBConfig;
    private final EventStoreConnectionManager eventStoreConnectionManager;
    private final ContextFactory contextFactory;

    public Adjudicator(CommandHandler commandHandler,
                       EventStoreDBConfig eventStoreDBConfig,
                       EventStoreConnectionManager eventStoreConnectionManager,
                       CurrentRevisionService currentRevision,
                       ContextFactory contextFactory) {
        this.commandHandler = commandHandler;
        this.eventStoreDBConfig = eventStoreDBConfig;
        this.eventStoreConnectionManager = eventStoreConnectionManager;
        this.currentRevision = currentRevision;
        this.contextFactory = contextFactory;
        this.retry = Retry.of("Adjudicator", RetryConfig.custom()
                .retryExceptions(WrongExpectedVersionException.class)
                .maxAttempts(3)
                .waitDuration(Duration.ofSeconds(2))
                .build());
    }

    /**
     * Adjudicates a transaction function and returns the result.
     *
     * @param <R> The return type
     * @param consumer The transaction function to execute
     * @return The result of the transaction
     */
    public <R> R adjudicateQuery(PDPTxFunction<R> consumer) throws PMException {
        NGACContext ctx = contextFactory.createContext();

        return ctx.pdp().runTx(contextFactory.createUserContext(ctx.pap()), pdpTx -> consumer.apply(ctx.pap(), pdpTx));
    }

    /**
     * Adjudicates a list of administrative commands.
     *
     * @param adminCommands The commands to adjudicate
     * @return A map of created node IDs
     */
    public List<Value> adjudicateAdminCommands(List<AdminCommand> adminCommands) throws PMException {
        List<Value> values = new ArrayList<>();

        adjudicateTransaction(ctx -> {
            UserContext userContext = contextFactory.createUserContext(ctx.pap());

            ctx.pdp().runTx(userContext, pdpTx -> {
                for (AdminCommand adminCommand : adminCommands) {
                    Value value = commandHandler.handleCommand(userContext, ctx, pdpTx, adminCommand);
                    values.add(value);
                }

                return null;
            });
        });

        return values;
    }

    /**
     * Executes a transaction consumer and returns the events.
     *
     * @param txConsumer The transaction consumer to execute
     * @return The list of events generated by the transaction
     */
    public List<PMEvent> adjudicateTransaction(PMConsumer<NGACContext> txConsumer) throws PMException {
        Supplier<List<PMEvent>> supplier = () -> {
            try {
                NGACContext ctx = contextFactory.createContext();
                txConsumer.accept(ctx);
                return publishEvents(ctx.pap());
            } catch (PMException e) {
                throw new PMRuntimeException(e);
            }
        };

        return executeWithRetry(supplier);
    }

    private <T> T executeWithRetry(Supplier<T> supplier) throws PMException {
        try {
            return Retry.decorateSupplier(retry, supplier).get();
        } catch (PMRuntimeException e) {
            Throwable cause = e.getCause();
            if (cause instanceof PMException p) {
                throw p;
            } else if (cause instanceof WrongExpectedVersionException w) {
                throw new PMException(w.getMessage());
            }

            throw e;
        }
    }

    private List<PMEvent> publishEvents(EventTrackingPAP pap) throws PMException {
        long revision = currentRevision.get();
        return pap.publishToEventStore(
                eventStoreConnectionManager.getOrInitClient(),
                eventStoreDBConfig.getEventStream(),
                revision
        );
    }
}