package gov.nist.csd.pm.pdp.resource.config;

import org.springframework.boot.context.properties.ConfigurationProperties;

import javax.annotation.PostConstruct;

@ConfigurationProperties(prefix = "pm.pdp.resource")
public class ResourcePDPConfig {

    /**
     * Admin PDP host name
     */
    private String adminHostname;

    /**
     * Admin PDP port
     */
    private int adminPort;

    /**
     * The mode of the EPP client: ASYNC, SYNC, or DISABLED. Default is ASYNC.
     */
    private EPPMode eppMode;

    /**
     * How long to wait for the events generated by the EPP to be processed locally by the event store subscription.
     * Time is in milliseconds.
     */
    private int eppSyncCatchUpTimeout;

    public ResourcePDPConfig() {
    }

    public ResourcePDPConfig(String adminHostname, int adminPort, EPPMode eppMode, int eppSyncCatchUpTimeout) {
        this.adminHostname = adminHostname;
        this.adminPort = adminPort;
        this.eppMode = eppMode;
        this.eppSyncCatchUpTimeout = eppSyncCatchUpTimeout;
    }

    @PostConstruct
    public void validate() {
        if (adminHostname == null || adminHostname.isEmpty() || adminHostname.equals("null")) {
            throw new IllegalArgumentException("adminHostname is null or empty");
        }

        if (adminPort == 0) {
            throw new IllegalArgumentException("adminPort is 0");
        }

        if (eppMode == null) {
            this.eppMode = EPPMode.ASYNC;
        }
    }

    public String getAdminHostname() {
        return adminHostname;
    }

    public void setAdminHostname(String adminHostname) {
        this.adminHostname = adminHostname;
    }

    public int getAdminPort() {
        return adminPort;
    }

    public void setAdminPort(int adminPort) {
        this.adminPort = adminPort;
    }

    public EPPMode getEppMode() {
        return eppMode;
    }

    public void setEppMode(EPPMode eppMode) {
        this.eppMode = eppMode;
    }

    public int getEppSyncCatchUpTimeout() {
        return eppSyncCatchUpTimeout;
    }

    public void setEppSyncCatchUpTimeout(int eppSyncCatchUpTimeout) {
        this.eppSyncCatchUpTimeout = eppSyncCatchUpTimeout;
    }
}
